version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: ppo_mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=tiny-es
    ports:
      - 27017:27017
    volumes:
      - ppo_mongo_data:/data/db
    networks:
      - ppo_network

  task-manager:
    image: ppo_task_manager
    container_name: ppo_task_manager
    restart: on-failure
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
    build: .
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    networks:
      - ppo_network

networks:
  ppo_network:
    name: ppo_network

volumes:
  ppo_mongo_data:
    name: ppo_mongo_data